#!/bin/bash

version=$1

# Clone nelson repo
git clone https://gitlab.com/semkodev/nelson.cli.git --branch v$version --single-branch

# Install required packages
npm install -g pkg yarn

# Change into nelson repo
cd nelson.cli

# Install packages
yarn install --pure-lockfile

# Create executable
pkg --targets=node10-linux-x64 --output ../services/nelson/files/usr/bin/nelson dist/nelson.js

# Change out of the nelson repo
cd ..

# Remove git repo
rm -Rf nelson.cli

# Remove existing
rm -f packages/nelson*

# Create DEB package
fpm \
--chdir services/nelson/files \
--version $version \
-s dir -t deb \
-n nelson \
-a noarch \
--after-install services/nelson/after-install.sh \
--after-remove services/nelson/after-remove.sh \
--deb-systemd services/nelson/nelson.service \
--deb-changelog services/nelson/changelogs/deb \
--maintainer "<semkodev@deviota>" \
--description "Nelson is a IRI neighbor discovery service created by Deviota" \
--url "https://gitlab.com/semkodev/nelson.cli" \
--package packages/ .

# Create RPM package
fpm \
--chdir services/nelson/files \
--version $version \
-s dir -t rpm \
-n nelson \
-a noarch \
--after-install services/nelson/after-install.sh \
--after-remove services/nelson/after-remove.sh \
--deb-systemd services/nelson/nelson.service \
--rpm-changelog services/nelson/changelogs/rpm \
--maintainer "<semkodev@deviota>" \
--description "Nelson is a IRI neighbor discovery service created by Deviota" \
--url "https://gitlab.com/semkodev/nelson.cli" \
--package packages/ .

# Clean binary
rm services/nelson/files/usr/bin/nelson
touch services/nelson/files/usr/bin/nelson
