#!/bin/bash

version=$1

# Remove existing
rm -f packages/ict*

curl -L https://github.com/iotaledger/ict/releases/download/$version/ict-$version.jar -o services/ict/files/var/lib/ict/ict.jar

# Create DEB package
fpm \
--chdir services/ict/files \
--version $version \
-s dir -t deb \
-n ict \
-a noarch \
--depends openjdk-8-jre-headless \
--after-install services/ict/after-install.sh \
--deb-systemd services/ict/ict.service \
--maintainer "<iota@foundation>" \
--description "Iota Controller AgentT" \
--url "https://github.com/iotaledger/ict/" \
--package packages/ .

# Create RPM package
fpm \
--chdir services/ict/files \
--version $version \
-s dir -t rpm \
-n ict \
-a noarch \
--depends java-1.8.0-openjdk-headless \
--rpm-systemd services/ict/ict.service \
--after-install services/ict/after-install.sh \
--maintainer "<iota@foundation>" \
--description "Iota Controller AgentT" \
--url "https://github.com/iotaledger/ict/" \
--package packages/ .
qq
