#!/bin/bash

version=$1

# Remove existing
rm -f packages/field*

# Update version of package
sed -i "s/{{version}}/$version/g" services/field/after-install.sh

# Create DEB package
fpm \
--chdir services/field/files \
--version $version \
-s dir -t deb \
-n field \
-a noarch \
--depends 'nodejs >= 8.9.4' \
--after-install services/field/after-install.sh \
--after-remove services/field/after-remove.sh \
--deb-systemd services/field/field.service \
--deb-changelog services/field/changelogs/deb \
--package packages/ .

# Create RPM package
fpm \
--chdir services/field/files \
--version $version \
-s dir -t rpm \
-n field \
-a noarch \
--depends 'nodejs >= 8.9.4' \
--after-install services/field/after-install.sh \
--after-remove services/field/after-remove.sh \
--deb-systemd services/field/field.service \
--rpm-changelog services/field/changelogs/rpm \
--package packages/ .

# Reset value
sed -i "s/$version/{{version}}/g" services/field/after-install.sh