#!/bin/bash

version=$1

# Clone nelson repo
git clone https://gitlab.com/semkodev/field.cli.git --branch v$version --single-branch

# Install required packages
npm install -g pkg yarn

# Change into field repo
cd field.cli

# Install packages
yarn install --pure-lockfile

# Create executable
pkg --targets=node10-linux-x64 --output ../services/field/files/usr/bin/field dist/field.js

# Change out of the field repo
cd ..

# Remove git repo
rm -Rf field.cli

# Remove existing
rm -f packages/field*

# Create DEB package
fpm \
--chdir services/field/files \
--version $version \
-s dir -t deb \
-n field \
-a noarch \
--after-install services/field/after-install.sh \
--after-remove services/field/after-remove.sh \
--deb-systemd services/field/field.service \
--deb-changelog services/field/changelogs/deb \
--maintainer "<semkodev@deviota>" \
--description "Field is a client for the IRI loadbalancer service created by Deviota" \
--url "https://gitlab.com/semkodev/field.cli" \
--package packages/ .

# Create RPM package
fpm \
--chdir services/field/files \
--version $version \
-s dir -t rpm \
-n field \
-a noarch \
--after-install services/field/after-install.sh \
--after-remove services/field/after-remove.sh \
--rpm-systemd services/field/field.service \
--rpm-changelog services/field/changelogs/rpm \
--maintainer "<semkodev@deviota>" \
--description "Field is a client for the IRI loadbalancer service created by Deviota" \
--url "https://gitlab.com/semkodev/field.cli" \
--package packages/ .

# Clean binary
rm services/field/files/usr/bin/field
touch services/field/files/usr/bin/field
