#!/bin/bash

version=$1

# Remove existing
rm -f packages/redix*

# Download Redix
curl -L https://github.com/alash3al/redix/releases/download/v$version/redix_linux_amd64.zip | gunzip -c > services/redix/files/usr/bin/redix-server
chmod +x services/redix/files/usr/bin/redix-server

# Create DEB package
fpm \
--chdir services/redix/files \
--version $version \
-s dir -t deb \
-n redix \
-a noarch \
--after-install services/redix/after-install.sh \
--deb-systemd services/redix/redix.service \
--maintainer "<alash3al@uflare>" \
--description "Redix Key-Value store" \
--url "https://github.com/alash3al/redix/" \
--package packages/ .

# Create RPM package
fpm \
--chdir services/redix/files \
--version $version \
-s dir -t rpm \
-n redix \
-a noarch \
--rpm-systemd services/redix/redix.service \
--after-install services/redix/after-install.sh \
--maintainer "<alash3al@uflare>" \
--description "Redix Key-Value store" \
--url "https://github.com/alash3al/redix/" \
--package packages/ .
