#!/bin/bash

version=$1

# Remove existing
rm -f packages/iri*

# Download latest IRI
curl -L https://github.com/iotaledger/iri/releases/download/v$version-RELEASE/iri-$version-RELEASE.jar -o services/iri/files/var/lib/iri/iri.jar

# Create DEB package
fpm \
--chdir services/iri/files \
--version $version \
-s dir -t deb \
-n iri \
-a noarch \
--depends openjdk-8-jre-headless \
--after-install services/iri/after-install.sh \
--deb-systemd services/iri/iri.service \
--deb-changelog services/iri/changelogs/deb \
--maintainer "<iota@foundation>" \
--description "IRI Reference Implementation from the IOTA Foundation" \
--url "https://github.com/iotaledger/iri" \
--package packages/ .

# Create RPM package
fpm \
--chdir services/iri/files \
--version $version \
-s dir -t rpm \
-n iri \
-a noarch \
--depends java-1.8.0-openjdk-headless \
--rpm-systemd services/iri/iri.service \
--after-install services/iri/after-install.sh \
--rpm-changelog services/iri/changelogs/rpm \
--maintainer "<iota@foundation>" \
--description "IRI Reference Implementation from the IOTA Foundation" \
--url "https://github.com/iotaledger/iri" \
--package packages/ .
